# Generated by Django 3.0.5 on 2020-08-17 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(default='', max_length=70, primary_key=True, serialize=False)),
                ('real_name', models.CharField(default='', max_length=200)),
                ('tz', models.CharField(default='', max_length=200)),
                ('all_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.All_members')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default='', max_length=200)),
                ('end_time', models.DateTimeField(default='', max_length=200)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Member')),
            ],
        ),
    ]
